#!/usr/bin/env python3
"""Recover captured fine iPhone tread on a physically thin floor sheet.

Only previously suppressed, fine, neutral, near-plane source floor records are
restored. Colors are exact original capture values. Their centers and compact
covariance are fitted to the measured floor; active original cable/equipment
records stay untouched. Imported floor web is explicitly marked for compaction.
"""
import argparse,json,shutil
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
from cleanup import ROOT,read_ply,write_ply,columns,sha256_file
from repair_surfaces import WORLD_FROM_RAW as W
from transfer_reference_floor import world


def alpha(v):return 1/(1+np.exp(-np.clip(v['opacity'].astype(float),-40,40)))

def main():
 ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--parent',type=Path,default=ROOT/'raw/ambulance-cleanup/pass6/floor-v5');ap.add_argument('--out',type=Path,required=True);args=ap.parse_args();report=json.loads((args.parent/'report.json').read_text());base=Path(report['baseline']);original_path=ROOT/'raw/ambulance_exp11_boot_sharp.ply';original,_,_=read_ply(original_path);baseline,_,_=read_ply(base/'iphone.ply');parent,_,_=read_ply(args.parent/'iphone.ply');refparent,_,_=read_ply(args.parent/'reference-patches.ply');refbase,_,_=read_ply(base/'reference-patches.ply');out=parent.copy();ref=refparent.copy();coef=np.array(report['floor_fit']['plane_y_from_xz1']);n=np.array([-coef[0],1,-coef[1]]);norm=np.linalg.norm(n);n/=norm;P=np.eye(3)-np.outer(n,n);R=report['region'];lo,hi=np.asarray(R['xz_bounds']);bench=np.asarray(R['bench_face_z_from_xy1'])
 def semantic(p):
  uv=p[:,[0,2]];edge=np.minimum(uv-lo,hi-uv).min(1);edge=np.minimum(edge,np.einsum('ij,j->i',p[:,:2],bench[:2])+bench[2]-p[:,2]-R['bench_face_minimum_front_clearance']);return edge
 p=world(original);d=(p[:,1]-np.einsum('ij,j->i',p[:,[0,2]],coef[:2])-coef[2])/norm;edge=semantic(p);a=alpha(original);ba=alpha(baseline);s=np.exp(columns(original,['scale_0','scale_1','scale_2']).astype(float));rgb=.5+.28209479177387814*columns(original,['f_dc_0','f_dc_1','f_dc_2']);candidate=(edge>.012)&(abs(d)<.010)&(s.max(1)<.015)&(a>.20)&(ba<a*.25)&(rgb.mean(1)>.12)&(rgb.mean(1)<.80)&(np.ptp(rgb,axis=1)<.18);ids=np.flatnonzero(candidate);Q=np.einsum('ij,njk->nik',W,Rotation.from_quat(columns(original[ids],['rot_1','rot_2','rot_3','rot_0'])).as_matrix());B=Q*s[ids,None,:];C=np.einsum('nik,njk->nij',B,B);sn=np.sqrt(np.einsum('i,nij,j->n',n,C,n));good=sn<.0035;ids=ids[good];C=C[good];Cp=np.einsum('ij,njk,lk->nil',P,C,P);ev,axes=np.linalg.eigh(Cp);major=np.clip(np.sqrt(np.maximum(ev[:,2],0)),.00065,.0030);minor=np.clip(np.sqrt(np.maximum(ev[:,1],0)),major/2.5,major);axes[:,:,0]=n;axes[:,:,1]-=np.einsum('ni,i->n',axes[:,:,1],n)[:,None]*n;axes[:,:,1]/=np.linalg.norm(axes[:,:,1],axis=1)[:,None];axes[:,:,2]=np.cross(n,axes[:,:,1]);newp=p[ids]-(d[ids]+.002)[:,None]*n;raw=np.einsum('ij,nj->ni',W.T,newp);quat=Rotation.from_matrix(np.einsum('ij,njk->nik',W.T,axes)).as_quat();new=original[ids].copy()
 for i,f in enumerate(['x','y','z']):new[f]=raw[:,i]
 for i,f in enumerate(['rot_1','rot_2','rot_3','rot_0']):new[f]=quat[:,i]
 new['scale_0']=np.log(.00015);new['scale_1']=np.log(minor);new['scale_2']=np.log(major)
 # Preserve the exact original color and opacity of each recovered source row.
 out[ids]=new
 mapping=np.load(base/'selections.npz')['reference_indices'];floorids=np.load(ROOT/'raw/ambulance-cleanup/pass4/floor-v4/reference-selection.npz')['indices'];rp=world(refbase);rd=(rp[:,1]-np.einsum('ij,j->i',rp[:,[0,2]],coef[:2])-coef[2])/norm;re=semantic(rp);oldchanges=np.load(args.parent/'changes.npz');delete=np.union1d(oldchanges['reference_delete_indices'],np.flatnonzero(np.isin(mapping,floorids)&(re>=R['edge_feather'])&(rd<.225)));ref['opacity'][delete]=np.float32(np.log(1e-8/(1-1e-8)));refchanged=np.zeros(len(ref),bool)
 for f in ref.dtype.names:refchanged|=ref[f]!=refbase[f]
 phonechanged=np.zeros(len(baseline),bool)
 for f in baseline.dtype.names:phonechanged|=out[:len(baseline)][f]!=baseline[f]
 args.out.mkdir(parents=True,exist_ok=True);write_ply(args.out/'iphone.ply',out);write_ply(args.out/'reference-patches.ply',ref);np.savez_compressed(args.out/'changes.npz',phone_changed_indices=np.flatnonzero(phonechanged),reference_changed_indices=np.flatnonzero(refchanged),phone_delete_indices=np.setdiff1d(oldchanges['phone_delete_indices'],ids),reference_delete_indices=delete,reference_original_capture_indices=mapping[np.flatnonzero(refchanged)],floor_anchor_reference_indices=oldchanges['floor_anchor_reference_indices'],recovered_original_phone_indices=ids)
 np.save(args.out/'recovered-original-phone-indices.npy',ids);shutil.copyfile(__file__,args.out/'generator.py');shutil.copy2(args.parent/'floor-support-sampling.npz',args.out/'floor-support-sampling.npz');shutil.copy2(args.parent/'floor-additions.ply',args.out/'floor-additions.ply');report['status']='Unreviewed actual fine iPhone floor recovery, fitted compact surface geometry';report['parent_patch']={'directory':str(args.parent),'report_sha256':sha256_file(args.parent/'report.json')};report['source_phone_sha256']=sha256_file(original_path);report['recovery']={'source':'original iPhone capture; only previously opacity-suppressed floor records','original_phone_rows_recovered':len(ids),'raw_ids_file':'recovered-original-phone-indices.npy','original_color_and_opacity_unchanged':True,'original_near_plane_height_max':.010,'original_max_sigma_max':.015,'original_normal_sigma_max':.0035,'normal_offset':-.002,'normal_sigma':.00015,'tangent_major_sigma_bounds':[.00065,.003],'maximum_tangent_anisotropy':2.5,'reference_floor_web_rows_for_physical_compaction':len(delete)};report['counts']={**report['counts'],'phone_geometrically_changed':len(ids),'phone_fine_floor_recovered':len(ids),'reference_deleted_on_final_compaction':len(delete),'already_invisible_floor_phone_rows_marked_for_physical_deletion':int(np.setdiff1d(oldchanges['phone_delete_indices'],ids).size)};report['checks']={'recovered_source_color_exact':all(np.array_equal(out[f][ids],original[f][ids]) for f in ['f_dc_0','f_dc_1','f_dc_2']),'recovered_source_opacity_exact':np.array_equal(out['opacity'][ids],original['opacity'][ids]),'active_original_cable_bed_equipment_unchanged':bool(np.all(ba[ids]<a[ids]*.25)),'unselected_phone_prefix_byte_exact':out[:len(baseline)][~phonechanged].tobytes()==baseline[~phonechanged].tobytes(),'floor_base_additions_unchanged':out[len(baseline):].tobytes()==parent[len(baseline):].tobytes(),'all_properties_finite':all(np.isfinite(v[f]).all().item() for v in [out,ref] for f in v.dtype.names),'recovery_all_near_plane':bool(np.max(abs(d[ids]))<.010)};report['collision_limitations']=[x for x in report['collision_limitations'] if 'Source bed' not in x]+['Source bed, wheel and active cable records stay unchanged; recovered previously hidden fine floor is fitted to a thin plane.'];report['generator_sha256']=sha256_file(args.out/'generator.py');report['changes_sha256']=sha256_file(args.out/'changes.npz');report['frozen_ply_hashes']={n:sha256_file(args.out/n) for n in ['iphone.ply','reference-patches.ply']};(args.out/'report.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'recovered_phone_rows':len(ids),'deleted_reference_rows':len(delete),'checks':report['checks']},indent=2))
if __name__=='__main__':main()
