#!/usr/bin/env python3
"""Delete rejected coarse floor films after geometric confinement.

The trial uses a stable-row opacity sentinel solely so the parent compositor
can physically remove exact IDs; report and manifest do not claim trial row
compaction. Fine captured floor and all original bed/cable geometry survive.
"""
import argparse,json,shutil
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
from cleanup import ROOT,read_ply,write_ply,columns,sha256_file
from constrain_floor_geometry import metrics
from transfer_reference_floor import world
from repair_surfaces import WORLD_FROM_RAW as W


def main():
 ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--baseline',type=Path,default=ROOT/'raw/ambulance-cleanup/pass5/combined-v1');ap.add_argument('--geometry-trial',type=Path,default=ROOT/'raw/ambulance-cleanup/pass6/floor-v3');ap.add_argument('--out',type=Path,required=True);args=ap.parse_args();report=json.loads((args.geometry_trial/'report.json').read_text());phone,_,_=read_ply(args.geometry_trial/'iphone.ply');ref,_,_=read_ply(args.geometry_trial/'reference-patches.ply');base,_,_=read_ply(args.baseline/'reference-patches.ply');mapping=np.load(args.baseline/'selections.npz')['reference_indices'];change=np.load(args.geometry_trial/'changes.npz');floor=np.load(ROOT/'raw/ambulance-cleanup/pass4/floor-v4/reference-selection.npz')['indices'];isfloor=np.isin(mapping,floor);p=world(base);Q=np.einsum('ij,njk->nik',W,Rotation.from_quat(columns(base,['rot_1','rot_2','rot_3','rot_0'])).as_matrix());s=np.exp(columns(base,['scale_0','scale_1','scale_2']).astype(float));coef=np.asarray(report['floor_fit']['plane_y_from_xz1']);d,sn,n=metrics(p,Q,s,coef);R=report['region'];lo,hi=np.asarray(R['xz_bounds']);edge=np.minimum(p[:,[0,2]]-lo,hi-p[:,[0,2]]).min(1);bench=np.asarray(R['bench_face_z_from_xy1']);edge=np.minimum(edge,np.einsum('ij,j->i',p[:,:2],bench[:2])+bench[2]-p[:,2]-R['bench_face_minimum_front_clearance']);core=edge>=R['edge_feather'];rgb=.5+.28209479177387814*columns(base,['f_dc_0','f_dc_1','f_dc_2'])
 P=np.eye(3)-np.outer(n,n);C=np.einsum('nik,njk->nij',Q*s[:,None,:],Q*s[:,None,:]);tangent=np.einsum('ij,njk,lk->nil',P,C,P);ev=np.linalg.eigvalsh(tangent);tmajor=np.sqrt(np.maximum(ev[:,2],1e-12));tminor=np.sqrt(np.maximum(ev[:,1],1e-12));needle=isfloor&core&(abs(d)<.022)&(tmajor>.025)&(tmajor/np.maximum(tminor,1e-6)>6)&(rgb.mean(1)>.30)&(np.ptp(rgb,axis=1)<.18)
 moved=change['reference_center_moved_indices'];film=moved[core[moved]];delete=np.union1d(film,np.flatnonzero(needle));out=ref.copy();out['opacity'][delete]=np.float32(np.log(1e-8/(1-1e-8)));args.out.mkdir(parents=True,exist_ok=True);write_ply(args.out/'iphone.ply',phone);write_ply(args.out/'reference-patches.ply',out);allchanged=np.zeros(len(base),bool)
 for name in base.dtype.names:allchanged|=base[name]!=out[name]
 np.savez_compressed(args.out/'changes.npz',phone_changed_indices=np.empty(0,np.int64),reference_changed_indices=np.flatnonzero(allchanged),phone_delete_indices=change['phone_delete_indices'],reference_delete_indices=delete,reference_original_capture_indices=mapping[np.flatnonzero(allchanged)],reference_film_delete_indices=film,reference_needle_delete_indices=np.flatnonzero(needle),reference_center_moved_indices=change['reference_center_moved_indices'],floor_anchor_reference_indices=change['floor_anchor_reference_indices'])
 report['status']='Unreviewed physical floor-film deletion trial; material coverage inspection required';report['parent_geometry_trial']={'directory':str(args.geometry_trial),'report_sha256':sha256_file(args.geometry_trial/'report.json')};report['deletion']={'reference_deleted_on_final_compaction':len(delete),'relocated_coarse_floor_film_rows':len(film),'oversized_bright_tangent_needles':int(needle.sum()),'criteria':{'film':'Detached material-support rows identified by V3 geometry trial, inside full-strength semantic floor region.','needle':{'absolute_original_height_max':.022,'tangent_major_sigma_min':.025,'tangent_anisotropy_min':6,'mean_dc_rgb_min':.30,'chroma_max':.18}},'stable_row_trial_sentinel_alpha':1e-8,'physically_removed_in_trial':0,'deleted_original_capture_ids':mapping[delete].tolist()};report['counts']['reference_geometrically_changed_and_retained']=int(np.setdiff1d(change['reference_changed_indices'],delete).size);report['checks']={'all_fields_finite':all(np.isfinite(out[f]).all().item() for f in out.dtype.names),'phone_byte_exact':sha256_file(args.out/'iphone.ply')==sha256_file(args.baseline/'iphone.ply'),'reference_color_and_SH_exact':all(np.array_equal(base[f],out[f]) for f in base.dtype.names if f.startswith('f_')),'deletion_alpha_at_compactor_floor':bool(np.all(1/(1+np.exp(-out['opacity'][delete].astype(float)))<=1.01e-8))};report['collision_limitations']+=['This deletion trial may expose incomplete material coverage; it must not ship without perspective review and any necessary measured thin surface repair.'];shutil.copyfile(__file__,args.out/'generator.py');report['generator_sha256']=sha256_file(args.out/'generator.py');report['changes_sha256']=sha256_file(args.out/'changes.npz');(args.out/'report.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'deleted_reference_rows':len(delete),'film_rows':len(film),'needles':int(needle.sum()),'checks':report['checks']},indent=2))
if __name__=='__main__':main()
